# Generated by Django 3.2.18 on 2023-03-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='table_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_table', to='booking.table'),
        ),
    ]
